[build]
  command = "npm run build"
  publish = "dist"  

[build.environment]
  NPM_FLAGS = "--ignore-scripts"  

[context.production]
  install = "npm install --force --loglevel=error"  

[build.processing]
  skip_processing = true